version: '3.8'

services:
  strapi:
    build:
      context: .
    image: my-strapi-app:latest
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - JWT_SECRET=your_jwt_secret
      - ADMIN_JWT_SECRET=your_admin_jwt_secret
    ports:
      - '1337:1337'
    depends_on:
      - db
    volumes:
      - ./public/uploads:/opt/app/public/uploads
      - ./src:/opt/app/src
    command: ["npx", "strapi", "start"]

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local